name: FireFFA
main: eu.fireblade.fireffa.Main
author: [Glowstoner, _goldocelot_]
version: Alpha v1.9.6
commands:
 kit:
  description: Cette commande vous give un kit specifique !
 tkit:
  description: Cette commande vous give un kit specifique !