name: FireFFA
main: eu.fireblade.fireffa.Main
author: [Glowstoner, _goldocelot_, baptistego]
version: Alpha v1.22.5
commands:
 kit:
  description: Cette commande vous give un kit specifique !
 tkit:
  description: Cette commande vous give un kit specifique !